// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Person.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Firstname            string   `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	City                 string   `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Iban                 string   `protobuf:"bytes,6,opt,name=iban,proto3" json:"iban,omitempty"`
	Time                 string   `protobuf:"bytes,7,opt,name=time,proto3" json:"time,omitempty"`
	Title                string   `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	Shirtsize            string   `protobuf:"bytes,9,opt,name=shirtsize,proto3" json:"shirtsize,omitempty"`
	PostalCode           int32    `protobuf:"varint,10,opt,name=postalCode,proto3" json:"postalCode,omitempty"`
	MacAdress            string   `protobuf:"bytes,11,opt,name=macAdress,proto3" json:"macAdress,omitempty"`
	Latitude             float32  `protobuf:"fixed32,12,opt,name=latitude,proto3" json:"latitude,omitempty"`
	JobTitle             string   `protobuf:"bytes,13,opt,name=jobTitle,proto3" json:"jobTitle,omitempty"`
	Currency             string   `protobuf:"bytes,14,opt,name=currency,proto3" json:"currency,omitempty"`
	Country              string   `protobuf:"bytes,15,opt,name=country,proto3" json:"country,omitempty"`
	CountryCode          string   `protobuf:"bytes,16,opt,name=countryCode,proto3" json:"countryCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_841ab6396175eaf3, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *Person) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Person) GetIban() string {
	if m != nil {
		return m.Iban
	}
	return ""
}

func (m *Person) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Person) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Person) GetShirtsize() string {
	if m != nil {
		return m.Shirtsize
	}
	return ""
}

func (m *Person) GetPostalCode() int32 {
	if m != nil {
		return m.PostalCode
	}
	return 0
}

func (m *Person) GetMacAdress() string {
	if m != nil {
		return m.MacAdress
	}
	return ""
}

func (m *Person) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Person) GetJobTitle() string {
	if m != nil {
		return m.JobTitle
	}
	return ""
}

func (m *Person) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Person) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Person) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func init() {
	proto.RegisterType((*Person)(nil), "main.Person")
}

func init() { proto.RegisterFile("Person.proto", fileDescriptor_841ab6396175eaf3) }

var fileDescriptor_841ab6396175eaf3 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x41, 0x4e, 0xc3, 0x30,
	0x10, 0x45, 0x95, 0x34, 0x49, 0x9b, 0x69, 0x29, 0xc8, 0x62, 0x31, 0x42, 0x08, 0x45, 0xac, 0xb2,
	0x62, 0xc3, 0x09, 0x10, 0x17, 0x40, 0x11, 0x17, 0x70, 0x12, 0x23, 0x06, 0x25, 0x76, 0x65, 0x3b,
	0x8b, 0x70, 0x20, 0xce, 0x89, 0x3c, 0x6e, 0xd2, 0xee, 0xe6, 0xbf, 0x27, 0x8f, 0xfe, 0xc8, 0x70,
	0xf8, 0x50, 0xd6, 0x19, 0xfd, 0x72, 0xb2, 0xc6, 0x1b, 0x91, 0x8d, 0x92, 0xf4, 0xf3, 0xdf, 0x06,
	0x8a, 0x88, 0xc5, 0x11, 0x52, 0xea, 0x31, 0xa9, 0x92, 0x3a, 0x6f, 0x52, 0xea, 0xc5, 0x23, 0x94,
	0x5f, 0x64, 0x9d, 0xd7, 0x72, 0x54, 0x98, 0x56, 0x49, 0x5d, 0x36, 0x17, 0x20, 0x1e, 0x60, 0x37,
	0xc8, 0xb3, 0xdc, 0xb0, 0x5c, 0xb3, 0xb8, 0x87, 0x5c, 0x8d, 0x92, 0x06, 0xcc, 0x58, 0xc4, 0x20,
	0x04, 0x64, 0x1d, 0xf9, 0x19, 0x73, 0x86, 0x3c, 0x07, 0x46, 0xad, 0xd4, 0x58, 0x44, 0x16, 0xe6,
	0xc0, 0x3c, 0x8d, 0x0a, 0xb7, 0x91, 0x85, 0x39, 0x6c, 0xf4, 0xe4, 0x07, 0x85, 0xbb, 0xb8, 0x91,
	0x43, 0x68, 0xe8, 0xbe, 0xc9, 0x7a, 0x47, 0xbf, 0x0a, 0xcb, 0xd8, 0x70, 0x05, 0xe2, 0x09, 0xe0,
	0x64, 0x9c, 0x97, 0xc3, 0xbb, 0xe9, 0x15, 0x02, 0xdf, 0x75, 0x45, 0xc2, 0xeb, 0x51, 0x76, 0x6f,
	0xbd, 0x55, 0xce, 0xe1, 0x3e, 0xbe, 0x5e, 0x41, 0xbc, 0xcf, 0x93, 0x9f, 0x7a, 0x85, 0x87, 0x2a,
	0xa9, 0xd3, 0x66, 0xcd, 0xc1, 0xfd, 0x98, 0xf6, 0x93, 0x0b, 0xdd, 0xc4, 0xdb, 0x97, 0x1c, 0x5c,
	0x37, 0x59, 0xab, 0x74, 0x37, 0xe3, 0x31, 0xba, 0x25, 0x0b, 0x84, 0x6d, 0x67, 0x26, 0xed, 0xed,
	0x8c, 0xb7, 0xac, 0x96, 0x28, 0x2a, 0xd8, 0x9f, 0x47, 0x2e, 0x7b, 0xc7, 0xf6, 0x1a, 0xb5, 0x05,
	0xff, 0xda, 0xeb, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9d, 0xa4, 0xc1, 0xb3, 0xc5, 0x01, 0x00,
	0x00,
}
